
data_dir: /home/wepeng/hyperbolic_vision/miniImageNet


exp:
    wandb: True
    wandb_api_key: 
    proj_name: H-resmlp
    exp_dir: ./runs
    exp_name: H_resmlp_final_miniImageNet_0.4
    device: auto
    log_freq: 20  # steps
    log_to_file: False
    log_to_stdout: True
    val_freq: 1   # epochs
    n_workers: 2
    pin_memory: True
    cache: 2     
entity: saitomar

hparams:
    restore_ckpt:
    freeze_weights: 
    seed: 0
    batch_size: 64
    start_epoch: 0
    n_epochs: 150
    l_smooth: 0.1
    device: auto
    num_classes: 100
    dataset: miniImageNet
    augment: False    

    
    model:
        type : lorentz_resmlp
        lorentz_resmlp:
            act : gelu
            num_blocks : 12
            channels : 196
            num_classes : 100
            image_resolution : [64,64]

    optimizer:
        opt_type: rsgd
        opt_kwargs:
          lr: 0.005
          weight_decay: 0.05
    
    scheduler:
        n_warmup: 20
        max_epochs: 150
        scheduler_type: cosine_annealing
        cosine_annealing:
          start_epoch: 40

    
